FROM node:18-alpine


# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# # Install npm dependencies
RUN npm install 
RUN npm install -g pm2

# Copy application files
COPY . .

# # Expose port
EXPOSE 5000

# # Start the application using pm2-runtime
CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "development"]